repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check
        language: python
        types_or: [ python, pyi ]
        args: [ "--fix" ]
        files: src_bot/

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        types_or: [ python, pyi ]
        files: src_bot/
